version: '3'
services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: fvtt
    ports: 
      - 30000:30000
    volumes:
      - /docker/foundrty/data:/data/foundryvtt
      - /docker/foundry/pkg:/host
      - /docker/foundry/app/resources/app:/opt/foundryvtt/resources/app
    restart: unless-stopped
